language: python

python:
  - "2.7"

install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION scipy=0.13.3 cython matplotlib biopython
  - source activate test-environment
  - conda install pytables=3.1.0
  - conda install -c https://conda.binstar.org/bcbio pysam
  - pip install pysqlite
  - pip install bx-python
  - pip install emase
  - python setup.py install

script:
  - python setup.py test
