# Setup
title:        GBRS
tagline:      Genotype-free genome reconstruction and ASE quantification from RNA-Seq data
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Kwangbom "KB" Choi
  url:        https://www.jax.org/research-and-faculty/faculty/research-scientists/kb-choi

# Gems
gems:
  - jekyll-paginate
  - github-pages
  - kramdown

#Others
markdown: kramdown
