#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys
import argparse
import gbrs

logo_text = """
        _
       | |
   __ _| |__  _ __ ___
  / _` | '_ \| '__/ __|
 | (_| | |_) | |  \__ \\
  \__, |_.__/|_|  |___/
   __/ |
  |___/     Ver.:%s

""" % gbrs.__version__


#
# Subcommand: hybridize
#
def add_subcommand_hybridize(subparsers):
    subparser_hyb = subparsers.add_parser('hybridize')
    pass


#
# Subcommand: align
#
def add_subcommand_align(subparsers):
    subparser_aln = subparsers.add_parser('align')
    pass


#
# Subcommand: bam2emase
#
def add_subcommand_bam2emase(subparsers):
    subparser_b2e = subparsers.add_parser('bam2emase')
    pass


#
# Subcommand: quantify
#
def add_subcommand_quantify(subparsers):
    subparser_quan = subparsers.add_parser('quantify')
    pass


#
# Subcommand: reconstruct
#
def add_subcommand_reconstruct(subparsers):
    subparser_rec = subparsers.add_parser('reconstruct')
    pass


#
# Subcommand: plot
#
def add_subcommand_plot(subparsers):
    subparser_plot = subparsers.add_parser('plot')
    subparser_plot.add_argument('-i', '--genoprob', action='store', dest='gpbfile', required=True)
    subparser_plot.add_argument('-o', '--outfile', action='store', dest='outfile', default='gbrs.plot.pdf')
    subparser_plot.add_argument('-n', '--sample-name', action='store', dest='sample_name', default='')
    subparser_plot.add_argument('--num-grids', action='store', dest='grid_size', default=42586)
    subparser_plot.add_argument('--xt-max', action='store', dest='xt_max', default=4501)
    subparser_plot.add_argument('--xt-size', action='store', dest='xt_size', default=475)
    subparser_plot.add_argument('--grid-width', action='store', dest='width', default=0.01)
    subparser_plot.set_defaults(func=gbrs.commands.plot)


def main():

    #
    # Main command parser
    #

    parser = argparse.ArgumentParser(version=gbrs.__version__)
    subparsers = parser.add_subparsers(dest='action')

    #
    # Add sub-commands
    #
    add_subcommand_hybridize(subparsers)
    add_subcommand_align(subparsers)
    add_subcommand_bam2emase(subparsers)
    add_subcommand_quantify(subparsers)
    add_subcommand_reconstruct(subparsers)
    add_subcommand_plot(subparsers)

    #
    # Execute command
    #
    args = parser.parse_args()
    if args.action is None:
        parser.print_help()
    else:
        kws = dict(vars(args))
        args.func(**kws)


if __name__ == "__main__":
    sys.exit(main())
